README.md, newsletters/2023-03-29-newsletter.md
=> 2023-03-29 release

newsletters/2023-06-21-newsletter.md
=> 2023-06-21 release

newsletters/2023-06-28-newsletter.md
=> 2023-06-28 release

newsletters/2023-08-30-newsletter.md, newsletters/2023-09-06-newsletter.md
=> 2023-09-06 release

newsletters/2023-09-13-newsletter.md
=> 2023-09-13 release

README.md, newsletters/2023-09-20-newsletter.md
=> 2023-09-20 release

newsletters/2023-10-31-newsletter.md, newsletters/2023-11-01-newsletter.md
=> 2023-10-31 release

newsletters/2023-11-08-newsletter.md
=> 2023-11-08 release

README.md, newsletters/2023-11-29-newsletter.md
=> 2023-11-29 release

README.md, newsletters/2023-12-06-newsletter.md
=> 2023-12-06 release

README.md, newsletters/2023-12-13-newsletter.md
=> 2023-12-13 release

README.md, newsletters/2023-12-13-newsletter.md, newsletters/2023-12-20-newsletter.md
=> 2023-12-20 release

README.md, newsletters/2023-12-27-newsletter.md
=> 2023-12-27 release

README.md, newsletters/2024-01-10-newsletter.md
=> 2024-01-10 release

newsletters/2024-01-17-newsletter.md
=> 2024-01-17 release

README.md
The Introduction to ZKML blog by Wordcoin was repeated twice.
At line 47 and 56.
=> fix: removed duplicate zkml resource

newsletters/2024-06-12-newsletter.md
=> 2024-06-12 release

newsletters/2024-07-10-newsletter.md
=> 2024-07-10 release

newsletters/2024-08-21-newsletter.md
=> 2024-08-21 release

newsletters/2024-10-23-newsletter.md, newsletters/2024-10-30-newsletter.md
=> 2024-10-23 release

newsletters/2024-11-06-newsletter.md
=> 2024-11-06 release

README.md, newsletters/2024-11-13-newsletter.md, newsletters/2024-11-20-newsletter.md
=> 2024-11-13 release

newsletters/2024-12-04-newsletter.md, newsletters/2024-12-11-newsletter.md
=> 2024-12-04 release
